T480: Minor changes.
    * gadd.sh
        * Moved it to .scripts/gadd and aesthetic changes inside it.

    * i3/scripts/
        * Aesthetic changes.

    * vimrc
        * Show ascii values when laststatus is set to 2.

Signed-off-by: Chinmay Chhajed <chinmay.chhajed@espressif.com>

diff --git a/linux/T480/.scripts/truespeed b/linux/T480/.scripts/truespeed
--- a/linux/T480/.scripts/truespeed
+++ b/linux/T480/.scripts/truespeed
@@ -2,7 +2,7 @@
 
 echo `date`>downspeed
 for((i=0;i<10;i++));do
-    (speedtest --version >/dev/null && speedtest --no-upload |grep ^Download >>$HOME/downspeed) || echo "Error, check speedtest-cli"
+    (speedtest --version >/dev/null && speedtest --no-upload |grep ^Download >>$HOME/downspeed) || echo "Error"
 done
 echo `date`>upspeed
 for((i=0;i<10;i++));do
